/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as ChatsRouteImport } from './routes/chats'
import { Route as CallsRouteImport } from './routes/calls'
import { Route as IndexRouteImport } from './routes/index'
import { Route as UUsernameRouteImport } from './routes/u.$username'
import { Route as PostIdRouteImport } from './routes/post.$id'
import { Route as ChatIdRouteImport } from './routes/chat.$id'
import { Route as CallIdRouteImport } from './routes/call.$id'
import { Route as GroupsInviteConversationIdRouteImport } from './routes/groups.invite.$conversationId'
import { Route as ApiEcosystemChatRouteRouteImport } from './routes/api/ecosystem/chat/route'
import { Route as ApiEcosystemActivityRouteRouteImport } from './routes/api/ecosystem/activity/route'
import { Route as ApiCallsTracksRouteRouteImport } from './routes/api/calls/tracks/route'
import { Route as ApiCallsSessionRouteRouteImport } from './routes/api/calls/session/route'
import { Route as ApiAiGenerateRouteRouteImport } from './routes/api/ai/generate/route'

const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const ChatsRoute = ChatsRouteImport.update({
  id: '/chats',
  path: '/chats',
  getParentRoute: () => rootRouteImport,
} as any)
const CallsRoute = CallsRouteImport.update({
  id: '/calls',
  path: '/calls',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const UUsernameRoute = UUsernameRouteImport.update({
  id: '/u/$username',
  path: '/u/$username',
  getParentRoute: () => rootRouteImport,
} as any)
const PostIdRoute = PostIdRouteImport.update({
  id: '/post/$id',
  path: '/post/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ChatIdRoute = ChatIdRouteImport.update({
  id: '/chat/$id',
  path: '/chat/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const CallIdRoute = CallIdRouteImport.update({
  id: '/call/$id',
  path: '/call/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const GroupsInviteConversationIdRoute =
  GroupsInviteConversationIdRouteImport.update({
    id: '/groups/invite/$conversationId',
    path: '/groups/invite/$conversationId',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiEcosystemChatRouteRoute = ApiEcosystemChatRouteRouteImport.update({
  id: '/api/ecosystem/chat',
  path: '/api/ecosystem/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiEcosystemActivityRouteRoute =
  ApiEcosystemActivityRouteRouteImport.update({
    id: '/api/ecosystem/activity',
    path: '/api/ecosystem/activity',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiCallsTracksRouteRoute = ApiCallsTracksRouteRouteImport.update({
  id: '/api/calls/tracks',
  path: '/api/calls/tracks',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCallsSessionRouteRoute = ApiCallsSessionRouteRouteImport.update({
  id: '/api/calls/session',
  path: '/api/calls/session',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAiGenerateRouteRoute = ApiAiGenerateRouteRouteImport.update({
  id: '/api/ai/generate',
  path: '/api/ai/generate',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/calls': typeof CallsRoute
  '/chats': typeof ChatsRoute
  '/settings': typeof SettingsRoute
  '/call/$id': typeof CallIdRoute
  '/chat/$id': typeof ChatIdRoute
  '/post/$id': typeof PostIdRoute
  '/u/$username': typeof UUsernameRoute
  '/api/ai/generate': typeof ApiAiGenerateRouteRoute
  '/api/calls/session': typeof ApiCallsSessionRouteRoute
  '/api/calls/tracks': typeof ApiCallsTracksRouteRoute
  '/api/ecosystem/activity': typeof ApiEcosystemActivityRouteRoute
  '/api/ecosystem/chat': typeof ApiEcosystemChatRouteRoute
  '/groups/invite/$conversationId': typeof GroupsInviteConversationIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/calls': typeof CallsRoute
  '/chats': typeof ChatsRoute
  '/settings': typeof SettingsRoute
  '/call/$id': typeof CallIdRoute
  '/chat/$id': typeof ChatIdRoute
  '/post/$id': typeof PostIdRoute
  '/u/$username': typeof UUsernameRoute
  '/api/ai/generate': typeof ApiAiGenerateRouteRoute
  '/api/calls/session': typeof ApiCallsSessionRouteRoute
  '/api/calls/tracks': typeof ApiCallsTracksRouteRoute
  '/api/ecosystem/activity': typeof ApiEcosystemActivityRouteRoute
  '/api/ecosystem/chat': typeof ApiEcosystemChatRouteRoute
  '/groups/invite/$conversationId': typeof GroupsInviteConversationIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/calls': typeof CallsRoute
  '/chats': typeof ChatsRoute
  '/settings': typeof SettingsRoute
  '/call/$id': typeof CallIdRoute
  '/chat/$id': typeof ChatIdRoute
  '/post/$id': typeof PostIdRoute
  '/u/$username': typeof UUsernameRoute
  '/api/ai/generate': typeof ApiAiGenerateRouteRoute
  '/api/calls/session': typeof ApiCallsSessionRouteRoute
  '/api/calls/tracks': typeof ApiCallsTracksRouteRoute
  '/api/ecosystem/activity': typeof ApiEcosystemActivityRouteRoute
  '/api/ecosystem/chat': typeof ApiEcosystemChatRouteRoute
  '/groups/invite/$conversationId': typeof GroupsInviteConversationIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/calls'
    | '/chats'
    | '/settings'
    | '/call/$id'
    | '/chat/$id'
    | '/post/$id'
    | '/u/$username'
    | '/api/ai/generate'
    | '/api/calls/session'
    | '/api/calls/tracks'
    | '/api/ecosystem/activity'
    | '/api/ecosystem/chat'
    | '/groups/invite/$conversationId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/calls'
    | '/chats'
    | '/settings'
    | '/call/$id'
    | '/chat/$id'
    | '/post/$id'
    | '/u/$username'
    | '/api/ai/generate'
    | '/api/calls/session'
    | '/api/calls/tracks'
    | '/api/ecosystem/activity'
    | '/api/ecosystem/chat'
    | '/groups/invite/$conversationId'
  id:
    | '__root__'
    | '/'
    | '/calls'
    | '/chats'
    | '/settings'
    | '/call/$id'
    | '/chat/$id'
    | '/post/$id'
    | '/u/$username'
    | '/api/ai/generate'
    | '/api/calls/session'
    | '/api/calls/tracks'
    | '/api/ecosystem/activity'
    | '/api/ecosystem/chat'
    | '/groups/invite/$conversationId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CallsRoute: typeof CallsRoute
  ChatsRoute: typeof ChatsRoute
  SettingsRoute: typeof SettingsRoute
  CallIdRoute: typeof CallIdRoute
  ChatIdRoute: typeof ChatIdRoute
  PostIdRoute: typeof PostIdRoute
  UUsernameRoute: typeof UUsernameRoute
  ApiAiGenerateRouteRoute: typeof ApiAiGenerateRouteRoute
  ApiCallsSessionRouteRoute: typeof ApiCallsSessionRouteRoute
  ApiCallsTracksRouteRoute: typeof ApiCallsTracksRouteRoute
  ApiEcosystemActivityRouteRoute: typeof ApiEcosystemActivityRouteRoute
  ApiEcosystemChatRouteRoute: typeof ApiEcosystemChatRouteRoute
  GroupsInviteConversationIdRoute: typeof GroupsInviteConversationIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chats': {
      id: '/chats'
      path: '/chats'
      fullPath: '/chats'
      preLoaderRoute: typeof ChatsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/calls': {
      id: '/calls'
      path: '/calls'
      fullPath: '/calls'
      preLoaderRoute: typeof CallsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/u/$username': {
      id: '/u/$username'
      path: '/u/$username'
      fullPath: '/u/$username'
      preLoaderRoute: typeof UUsernameRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/post/$id': {
      id: '/post/$id'
      path: '/post/$id'
      fullPath: '/post/$id'
      preLoaderRoute: typeof PostIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chat/$id': {
      id: '/chat/$id'
      path: '/chat/$id'
      fullPath: '/chat/$id'
      preLoaderRoute: typeof ChatIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/call/$id': {
      id: '/call/$id'
      path: '/call/$id'
      fullPath: '/call/$id'
      preLoaderRoute: typeof CallIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/groups/invite/$conversationId': {
      id: '/groups/invite/$conversationId'
      path: '/groups/invite/$conversationId'
      fullPath: '/groups/invite/$conversationId'
      preLoaderRoute: typeof GroupsInviteConversationIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/ecosystem/chat': {
      id: '/api/ecosystem/chat'
      path: '/api/ecosystem/chat'
      fullPath: '/api/ecosystem/chat'
      preLoaderRoute: typeof ApiEcosystemChatRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/ecosystem/activity': {
      id: '/api/ecosystem/activity'
      path: '/api/ecosystem/activity'
      fullPath: '/api/ecosystem/activity'
      preLoaderRoute: typeof ApiEcosystemActivityRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/calls/tracks': {
      id: '/api/calls/tracks'
      path: '/api/calls/tracks'
      fullPath: '/api/calls/tracks'
      preLoaderRoute: typeof ApiCallsTracksRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/calls/session': {
      id: '/api/calls/session'
      path: '/api/calls/session'
      fullPath: '/api/calls/session'
      preLoaderRoute: typeof ApiCallsSessionRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/ai/generate': {
      id: '/api/ai/generate'
      path: '/api/ai/generate'
      fullPath: '/api/ai/generate'
      preLoaderRoute: typeof ApiAiGenerateRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CallsRoute: CallsRoute,
  ChatsRoute: ChatsRoute,
  SettingsRoute: SettingsRoute,
  CallIdRoute: CallIdRoute,
  ChatIdRoute: ChatIdRoute,
  PostIdRoute: PostIdRoute,
  UUsernameRoute: UUsernameRoute,
  ApiAiGenerateRouteRoute: ApiAiGenerateRouteRoute,
  ApiCallsSessionRouteRoute: ApiCallsSessionRouteRoute,
  ApiCallsTracksRouteRoute: ApiCallsTracksRouteRoute,
  ApiEcosystemActivityRouteRoute: ApiEcosystemActivityRouteRoute,
  ApiEcosystemChatRouteRoute: ApiEcosystemChatRouteRoute,
  GroupsInviteConversationIdRoute: GroupsInviteConversationIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
